# This option fixes the logging error
options:
  logging: CLOUD_LOGGING_ONLY

steps:
# 1. Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'us-central1-docker.pkg.dev/kaif11/kaif-python-repo/flask-app:v1',
    '.'
  ]

# 2. Push the new image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'us-central1-docker.pkg.dev/kaif11/kaif-python-repo/flask-app:v1'
  ]

# 3. Update the running Compute Engine instance
- name: 'gcr.io/google-cloud-sdk/gcloud'
  args: [
    'compute',
    'instances',
    'update-container',
    'kaif-app-instance',
    '--container-image', 'us-central1-docker.pkg.dev/kaif11/kaif-python-repo/flask-app:v1',
    '--zone', 'us-central1-a'
  ]

# Store the final image in the registry
images:
- 'us-central1-docker.pkg.dev/kaif11/kaif-python-repo/flask-app:v1'
